### ISSUE TITLE
Sheet 4 - Exercise 1 - Relaxation: Add check for edge data "x" in verify script

### ISSUE THREAD

**Issue by gabriel-gehrke** [tubs-alg/AlgLab-Summer-24#10]
The task requires implementing edge attributes called "x" for every edge in the graph in which the (fractional) assignments of the variables are stored. If the student failed to do so, the error message looks rather cryptic.

Traceback (most recent call last):
  File ".../04_mip/exercises/01_tsp/_alglab_utils.py", line 192, in <module>
    exec(exc_file, glob)
  File "<string>", line 157, in <module>
  File "<string>", line 40, in att48
  File "<string>", line 19, in _connected
TypeError: '>=' not supported between instances of 'NoneType' and 'float'

A simple check that assures that all edges in the solution graph have data("x") defined would be helpful.

**Comment by d-krupke** [comment]
Agreed. Can you please take care of this?
